language: cpp
sudo: required
git:
  depth: 3
cache:
  directories:
    - release
    - blockscipy/build
    - .mtime_cache
    - $HOME/.local
    - $HOME/.cache/pip
matrix:
  include:
    - stage: Build C++ Library
      dist: xenial
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7
      before_install: .travis/build_ubuntu_cpp.sh
      script: .travis/compile_ubuntu_cpp.sh

