language: cpp
dist: xenial
sudo: required
git:
  depth: 3
env: PYTHONPATH=$PYTHONPATH:/usr/local/cmake-3.9.2/bin/
cache:
  pip: true
  directories:
    - release
    - blockscipy/build
    - .mtime_cache
matrix:
  include:
    - stage: Build Core Library (CPP)
      before_install: .travis/build_ubuntu_cpp.sh
      install: .travis/compile_ubuntu_cpp.sh
      script: .travis/test_parser.sh
    - stage: Build Python Module
      before_install:
        - .travis/build_ubuntu_cpp.sh
        - .travis/build_ubuntu_python.sh
      install:
        - .travis/compile_ubuntu_cpp.sh
        - .travis/compile_ubuntu_python.sh
      script: .travis/test_python.sh
