
name: blocksci-env

dependencies:
  - python=3.5
  - boost
  - lmdb
  - sparsehash
  - jsoncpp
  - numpy
  - matplotlib
  - pandas
  - pip
  - cmake
  - setuptools
  - requests
  - pycrypto
  - multiprocess
  - psutil
  - dateparser
